apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
spec:
  selector:
    app: mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---

apiVersion: v1
kind: Secret
metadata:
    name: mongo-db-secret
type: Opaque
data:
    # echo -n 'password' | base64
    mongo-root-username: bW9uZ29kYg== # mongodb
    mongo-root-password: cGFzc3dvcmQ= # password

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-db-configmap
data:
  database_url: mongo-db-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo:jammy
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongo-db-secret
                  key: mongo-root-password

